mlp:
  input_dim: 384
  hidden_dims: [256, 128]
  dropout: 0.3
  output_dim: 2
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
  early_stopping_patience: 3
  model_path: "results/mlp_model.pth"  # ← Fixed! Usare .pth per MLP (PyTorch)

svm:
  kernel: "linear"
  C: 1.0
  model_path: "results/svm_model.pkl"  # ← OK, .pkl per SVM (joblib)
